# Handling Missing Data with SimpleImputer

**Import Required Libraries**

In [2]:
# import numpy
import numpy as np
# importing sklearn
import sklearn
# importing simpleimputer
from sklearn.impute import SimpleImputer

**Performing “Mean” Imputation**

In [3]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
age = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_mean.transform(age))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


**Performing “Median” Imputation**


In [7]:
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
imp_median.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
age = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_median.transform(age))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


**Performing “Most_frequent” Imputation**


In [18]:
imp_mf = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imp_mf.fit([["one", 'two', 'three'], ['four', np.nan, 'six'], ['one', 'two', 'two']])

category = [[np.nan, 'two', 'two'], ['four', np.nan, 'six'], ['ten', np.nan, 'nine']]

print(imp_mf.transform(category))

[['one' 'two' 'two']
 ['four' 'two' 'six']
 ['ten' 'two' 'nine']]


**Performing “Constant” Imputation**


In [17]:
imp_constant = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value=20)
imp_constant.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
age = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_constant.transform(age))

[[20.  2.  3.]
 [ 4. 20.  6.]
 [10. 20.  9.]]
